### ISSUE TITLE
Spaces, dashes and other obscurities

### ISSUE THREAD

**Issue by aliatli** [BilkentCS-319/Xtrify#4]
note headings cant have spaces for some reason.
note names dont support unrecognized characters.
keywords extraction fails when there is unrecognized characters.

**Comment by usamasaqib** [comment]
try this.
Add the following comment at the beginning of each .py file
< # -*- coding: utf-8 -*- >
NOTE: IGNORE THE BRACKETS ( <, >). I ADDED THOSE CAUSE GITHUB F**KS UP THE COMMENT
Secondly define all unicode encoded texts as x = u"foo"

I have done this in rake.py, so now it is accepting weird characters.
