### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by aliatli** [BilkentCS-319/Xtrify#5]
recommendation returns only title.
arxiv database seems very limited, we should try something that returns much more results.

**Comment by sedagulkesen** [comment]
Could you please specify what we need more about the papers we are going to recommend? Additionally, the output of the Recommendation system currently includes the urls of the respective papers' too. If you can iterate through the results taken from the search method, you can see that it has tuples if [title,url]. An example output is as the following 
![image1](https://user-images.githubusercontent.com/23726743/28745652-4abec3aa-7485-11e7-92da-f1f741bbaf33.jpg)
For the other specifications you need, can you please have a look at this block. We can add the info that you want to the returned array.
![image2](https://user-images.githubusercontent.com/23726743/28745658-60a964ae-7485-11e7-8556-8d5bc7ac2c19.jpg)
Ps. The reason arXiv is chosen is that it has an access to a huge database and the API is completely free to use! They don't even limit the number of requests.
