### ISSUE TITLE
Extraction

### ISSUE THREAD

**Issue by sedagulkesen** [BilkentCS-319/Xtrify#7]
When i want to apply keyword extraction the note that I saved, i got an error. The corresponding note and the error code are shown as following,
<img width="807" alt="screen shot 2017-07-30 at 16 58 51" src="https://user-images.githubusercontent.com/23726743/28754215-d2901cce-7549-11e7-8dff-a71c91828e3e.png">
<img width="1440" alt="screen shot 2017-07-30 at 16 58 59" src="https://user-images.githubusercontent.com/23726743/28754216-d5e5cefa-7549-11e7-870a-e9fd47c4b64c.png">

When i searched the error code, i've found this solution,
https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20

I guess the problem in note class in the 155th line.

**Comment by usamasaqib** [comment]
The problem is that our code is not recognizing the unicode value for '-'
If you remove '-' (dash) from your note it should work. The solution to this problem is to tell our code to use utf-8 encoding rather than ascii encoding
